basicapp/urls.py
from django.urls import path
from basicapp import views

app_name = 'basicapp'
urlpatterns=[
    path('relative/',views.rel,name='relative'),
    path('other',views.other,name='other'),

]

learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basicapp import views
urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basicapp/',include('basicapp.urls'))
]

basicapp/models.py
from django.db import models

# Create your models here.

basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):

    return render(request,'basic_app/index.html')


def other(request):
    return render(request,'basic_app/other.html')

def rel(request):
    return render(request,'basic_app/rel.html')

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to index</h1>

  </body>
</html>

learning_templates/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    
  </body>
</html>

learning_templates/templates/basicapp/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to index</h1>

  </body>
</html>

learning_templates/templates/basicapp/other.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to Other</h1>
  </body>
</html>

learning_templates/templates/basicapp/rel.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>welcome to rel temp</h1>
    <a href="{% url 'basicapp:other' %}"></a>
  </body>
</html>